name: Enable Auto-Merge

on:
  workflow_run:
    workflows: ["tests.yml"]
    types:
      - completed

jobs:
  enable-auto-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    env:
      WORKFLOW_SHA: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: Find Pull Request for SHA
        uses: actions/github-script@v7
        id: get-pr
        with:
          script: |
            const prList = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
            });

            const match = prList.data.find(p => p.head.sha === process.env.WORKFLOW_SHA);

            if (!match) {
              throw new Error("PR not found for SHA " + process.env.WORKFLOW_SHA);
            }

            core.setOutput("pr_number", match.number);

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.get-pr.outputs.pr_number }}
          merge-method: squash
